language: groovy

script: echo 'Nothing to do'

before_deploy:
  - cd aws-eb
  - ./gradlew clean buildZip

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: I2tj+dLKtguKSbl1Sl75A9kIXmZIvlcR0yJ27L4aP106PjRD6FhuwW8ppr1W9Q6Ezaz5EhsZCRBKegGKvTSWHrJDhNgP1WL4EvzyRQFfcjHT/yKzmUTh9/p7y3/740usIrIvIgXosqzyUr+yO30XIffjnZB8rDqpd+mir8MqkxCb6K53a5zGg1GwmKNQuCut7DX/iqVaLzWkokw7p0aYKvw0k2FMHcUGALK9zJNR92x3LLZefWLtykWd5zCnBry3besSho/gOMKRIYRcYm5QuYfKaQMd7jEtpdTBZTqBxGX3YWE1PLg533nqw++DZQw/BJYpAZk9tIx0EEqbs9cpbYqeBvk7KyvBnQMH7NFSKqd5r7PFEugK4htr4XugOjhhCkPTi1b/PhhY+S563iRSsyHA2iSuCUzn58kezfDeC6xBQtFL0RfDNmssXH2kf9Vham+jmVDkqXWwU6gTLf4tqpuhGmLuT9jTmoG/c3f5iXpxGLFnj/vnuTFiue4vPaU+VgHc2wbln7LnMN0VtqqTheg0uDVr8rCOqj6fBFCpz9o+HVNKVdgn8DFgA8cTR3rgEfyfF0Q5g5ZBjsoo1OT5e7wvp+u+jAV/0YMmyNksyCIw7/scLsb+FcWeVDQR5+Zql0jEJxDw6nLTQkTe6YPSwd7OQhG6x3HjzTSYQZDwnr8=
  file: aws-eb/build/docker-sonarqube.zip
  on:
    repo: musketyr/docker-sonarqube
    tags: true
